/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SIG.view;
import SIG.controller.ActionListenerBtns;
import SIG.controller.ActionListenerMenuItems;
import SIG.model.InvoiceHeader;
import java.util.ArrayList;
/**
 *
 * @author mary
 */
public class SIG_Frame extends javax.swing.JFrame {
    /**
     * Creates new form SIG_Frame
     */
    public SIG_Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Invoice = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_Items = new javax.swing.JTable();
        jButton_Create = new javax.swing.JButton();
        jButton_Create.addActionListener(listenerBtns);
        jButton_Delete = new javax.swing.JButton();
        jButton_Delete.addActionListener(listenerBtns);
        jButton_Save = new javax.swing.JButton();
        jButton_Save.addActionListener(listenerBtns);
        jButton_Cancle = new javax.swing.JButton();
        jButton_Cancle.addActionListener(listenerBtns);
        jLabel_InNumber = new javax.swing.JLabel();
        jLabel_InDate = new javax.swing.JLabel();
        jLabel_CustomerName = new javax.swing.JLabel();
        jLabel_InTotal = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel_InTotal1 = new javax.swing.JLabel();
        jLabel_InTotal2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuIteamLoadFile = new javax.swing.JMenuItem();
        jMenuItemSavveFile = new javax.swing.JMenuItem();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(750, 550));
        setSize(new java.awt.Dimension(700, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_Invoice.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable_Invoice);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 300, 343));

        jTable_Items.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jTable_Items);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 370, 220));

        jButton_Create.setText("Create New Invoice");
        jButton_Create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CreateActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Create, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        jButton_Delete.setText("Delete Invoice");
        jButton_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DeleteActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, -1, -1));

        jButton_Save.setText("Save");
        getContentPane().add(jButton_Save, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 420, -1, -1));

        jButton_Cancle.setText("Cancel");
        getContentPane().add(jButton_Cancle, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 420, -1, -1));

        jLabel_InNumber.setText("Invoice Number");
        getContentPane().add(jLabel_InNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 88, -1));

        jLabel_InDate.setText("Invoice Date");
        getContentPane().add(jLabel_InDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 88, -1));

        jLabel_CustomerName.setText("Customer Name");
        getContentPane().add(jLabel_CustomerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 88, 20));

        jLabel_InTotal.setText("Invoice Items");
        getContentPane().add(jLabel_InTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 98, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, 176, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, 196, -1));

        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, 48, -1));

        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, 44, -1));

        jLabel_InTotal1.setText("Invoice Total");
        getContentPane().add(jLabel_InTotal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 98, -1));

        jLabel_InTotal2.setText("Invoices Table");
        getContentPane().add(jLabel_InTotal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 98, 30));

        jMenu1.setText("File");

        jMenuIteamLoadFile.setText("Load File");
        jMenuIteamLoadFile.addActionListener(listenerMenuItems);
        jMenu1.add(jMenuIteamLoadFile);

        jMenuItemSavveFile.setText("Save File");
        jMenuItemSavveFile.addActionListener(listenerMenuItems);
        jMenuItemSavveFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSavveFileActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemSavveFile);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_CreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CreateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_CreateActionPerformed

    private void jButton_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_DeleteActionPerformed

    private void jMenuItemSavveFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSavveFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemSavveFileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SIG_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SIG_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SIG_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SIG_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SIG_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Cancle;
    private javax.swing.JButton jButton_Create;
    private javax.swing.JButton jButton_Delete;
    private javax.swing.JButton jButton_Save;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel_CustomerName;
    private javax.swing.JLabel jLabel_InDate;
    private javax.swing.JLabel jLabel_InNumber;
    private javax.swing.JLabel jLabel_InTotal;
    private javax.swing.JLabel jLabel_InTotal1;
    private javax.swing.JLabel jLabel_InTotal2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuIteamLoadFile;
    private javax.swing.JMenuItem jMenuItemSavveFile;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable_Invoice;
    private javax.swing.JTable jTable_Items;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

  private   ActionListenerBtns listenerBtns= new ActionListenerBtns(this);
    private  ActionListenerMenuItems listenerMenuItems=new ActionListenerMenuItems(this);
    private ArrayList<InvoiceHeader> invoicesArr;

    public void setInvoicesArr(ArrayList<InvoiceHeader> invoicesArr) {
        this.invoicesArr = invoicesArr;
    }
    
    public InvoiceHeader getInvoiceHeaderObject(int code){
        for(InvoiceHeader InvoiceHeaderObject : invoicesArr){
            if(InvoiceHeaderObject.getNumber()==code){
                return InvoiceHeaderObject;
            }
        }
        return null;  
    }
    

}
